### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by PiotrCh-PGS** [PGSSoft/php-docker-skeleton#6]
Docker images built (step 1) then trying to run getting following error:
ERROR: Error: image library/pgsdemo:0.0.1-php7 not found

**Comment by partikus** [comment]
@PiotrCh-PGS Did you try to run `./docker.sh build-images` before?

**Comment by PiotrCh-PGS** [comment]
Yup, twice :)

**Comment by partikus** [comment]
@PiotrCh-PGS more details please

**Comment by PiotrCh-PGS** [comment]
![image](https://cloud.githubusercontent.com/assets/21058588/18876155/dddfddde-84c8-11e6-8902-44ba6e0626cf.png)

If you need anything else let me know.

**Comment by partikus** [comment]
Image that you sent indicate you have no required images, please put `docker images | grep pgsdemo` output

**Comment by PiotrCh-PGS** [comment]
No such image

![image](https://cloud.githubusercontent.com/assets/21058588/18876112/b81513d0-84c8-11e6-8b01-50e19aad85ac.png)

**Comment by PiotrCh-PGS** [comment]
When I execute one build only
`docker build --no-cache=TRUE -t "demo:0.0.1-php7" --build-arg USERID="1000" docker/php7`

Then at the end I can see something like this:
`Step 9 : COPY entrypoint.sh /entrypoint.sh
stat /var/lib/docker/aufs/mnt/e488669c833087cda135e4ac2370953877fa6a5cf8ba2309cdc63fce2749b660/entrypoint.sh: no such file or directory`

**Comment by partikus** [comment]
@PiotrCh-PGS please let me know what docker/docker-compose version do you use, more details about OS and env

**Comment by PiotrCh-PGS** [comment]
Docker version 1.12.1
docker-compose version 1.5.2
Kubuntu 16.04

**Comment by partikus** [comment]
@PiotrCh-PGS any progress?

**Comment by PiotrCh-PGS** [comment]
There was a problem with docker service, restart did the job.
